### ISSUE TITLE
AxiosError: Request failed with status code 406

### ISSUE THREAD

**Issue by abcklaus** [TA2k/ioBroker.tedee#3]
From time to time I am not able to open the lock from iobroker. The log shows the following issue:

<img width="897" alt="image" src="https://github.com/TA2k/ioBroker.tedee/assets/60260208/4d3a0804-add8-4938-8921-24dd9bfa96c2">

Any idea about the root cause?

**Comment by TA2k** [comment]
Please retest with tedee bridge firmware 2.2.20263

**Comment by TA2k** [comment]
Please test also the GitHub version of the adapter

**Comment by abcklaus** [comment]
ok, I have updated the FW and the adapter. I will observe and check if the issue occurs again.

Thanks for your help.

**Comment by TA2k** [comment]
Do you have an update on this issue?

**Comment by abcklaus** [comment]
The issue didn’t occur again.

thank you for your support.
